### ISSUE TITLE
A list of what Pantella does different? 

### ISSUE THREAD

**Issue by Ainaemaet** [Pathos14489/Pantella#13]
Hello, just got Mantella up and running tonight (it's amazing) and then I stumbled on this while searching for some tweaks to it. 

I've heard some people saying Pantella is more feature-rich (well, one guy anyhow lol) and so my curiosity is piqued. 

From the front page of this fork however, I can't tell what is or isn't different at all really - and I don't see a link to a discord or anywhere else where I might learn. 

Can someone explain what is different between this fork and Mantella, and maybe some pros/cons to this one in comparison (or link me to somewhere I can find out?)?. 

Thanks!

**Comment by Pathos14489** [comment]
Hi! Sorry for the late reply. I typically respond faster on Discord.

Pantella has been more or less redesigned from the ground up forked from Mantella v0.11. A lot of the systems have been broken out into generic modules to make it easier for developers to add new LLM backends, change how conversations are stepped through, etc., without having to redo any of the work for the parts they don't want to replace. It also gives end users much finer control over the exact shape of the prompt sent to the LLM with the prompt_style settings. xTTS and PiperTTS are both included with Pantella by default, and the launcher has been pre-setup to cut out any preparation steps. xVASynth is currently the only TTS that requires extra steps to get working because I can't include it by default.

Pantella has a completely new memory system that depreciates the old summary memory. The new memory uses chromadb to more or less sort everything you've ever said to an NPC into the most relevant chunks of memories. No more lossy summaries that forget details because the LLM doesn't know to include them/can't shove everything into one paragraph.

Pantella also has a completely revamped NPC behaviors system that has been made as easy to program f for as possible to let the NPC choose to do more complex actions than the pre built "Follow" and "Attack" behaviors from Mantella. Lemme know if you want details on how to make your own behaviors.
Pantella additionally has completely reworked generation processing to basically read the output text and figure out which chunks should be spoken by the NPC and which chunks should be read by the new Narrator, which reads roleplayed actions in asterisks by default but can be set to other roleplaying styles in settings.

And Pantella also just got a new add-on system to let other mod authors create self contained patches for Pantella to add voice models and character entries without having to tinker around in the source much, remember where the models should go for each TTS, etc. Just drop in the add-ons folder and it should work. This is the most recent addition though and it's a bit buggy and not feature complete but I still think it's cool and with mentioning.

There's more small details but that's the big features that I feel personally set Pantella apart the most. Admittedly some of the more technical changes to make things easier to add on to are going to be lost on non-developers and I'm not great at advertising tbh but hopefully I've sold it as being pretty cool.

If you would like to get a more in depth run down on things than this, feel free to join the Discord over here: https://discord.gg/M7Zw8mBY6r
I also am planning to finally get around to updating the README soon, so stay tuned. <3
